### ISSUE TITLE
Help! When I start mc-pre4 I have no model platform

### ISSUE THREAD

**Issue by TrinityCraft** [MrCrayfish/ModelCreator#131]
When I start mc-pre4 I have no model platform, I have tried with both java 7 and 8, and both the windows and universal.
I'm running windows 10 (and yes I've tried compatibility mode)

**Comment by TrinityCraft** [comment]
Please some one help

**Comment by AndersBillLinden** [comment]
Post a screenshot.

**Comment by TrinityCraft** [comment]
![faliure](https://cloud.githubusercontent.com/assets/24579356/21817078/63020d2a-d717-11e6-9a71-1e3f225f879f.png)

So yea, I've tried everything I reinstalled java 6 different times, I've run it in compatibility mode. I just really don't know what's going on. I used it before on windows 7 and it worked fine, now on windows 10 it doesn't.

Here's a video of what happens when I open it
[Video.zip](https://github.com/MrCrayfish/ModelCreator/files/696866/Video.zip)

**Comment by TrinityCraft** [comment]
Sorry the screenshot got cut off a bit

**Comment by AndersBillLinden** [comment]
Thanks for the screenshot and the video. Did you install the driver to the graphics card properly?

**Comment by TrinityCraft** [comment]
yea, it's nothing wrong with my drivers

**Comment by AndersBillLinden** [comment]
I see you do even get the splash (welcome screen). Do you have trouble closing the application as well?

**Comment by AndersBillLinden** [comment]
I got the same symptoms now when I tried for a lot of times. Then the problems dissapeared and now, I can always run it.

**Comment by AndersBillLinden** [comment]
Are you willing to test it in eclipse?

**Comment by TrinityCraft** [comment]
yea, I'm willing to test it in eclipse, and yea, the X button doesn't close the aplication, just the window

**Comment by AndersBillLinden** [comment]
Did you manage to run it in eclipse?

**Comment by TrinityCraft** [comment]
I'd download the master right?

**Comment by AndersBillLinden** [comment]
Yeah! It sounds like you found the download link!

**Comment by TrinityCraft** [comment]
Yea just give me a bit, I have to redownload eclipse

**Comment by TrinityCraft** [comment]
Found the problem, it's the camera java file. It's full of errors, can't figure out how to fix it. I'm better With c# I'm attaching a copy, maybe you can figure it out.
[Camera.zip](https://github.com/MrCrayfish/ModelCreator/files/706237/Camera.zip)

**Comment by TrinityCraft** [comment]
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	String cannot be resolved to a type
	Double cannot be resolved to a type
	Double cannot be resolved
	System cannot be resolved
	JOptionPane cannot be resolved
	System cannot be resolved
	Properties cannot be resolved to a type
	Properties cannot be resolved to a type
	FastLookAndFeel cannot be resolved
	UIManager cannot be resolved
	Exception cannot be resolved to a type
	String cannot be resolved to a type
	String cannot be resolved to a type

	at src.com.mrcrayfish.modelcreator.Start.main(Start.java:12)




That's what I get when I try to run Start.java

**Comment by TrinityCraft** [comment]
So the problem isn't that the model platform isn't there, it's that the camera isn't loading, therefore you can't see the model platform...

**Comment by AndersBillLinden** [comment]
Which version of java did you install?

**Comment by AndersBillLinden** [comment]
Those classes should be present, there is nothing wrong with Camera.java. Java 8 is the current version.

**Comment by TrinityCraft** [comment]
Hm maybe I have the wrong java version

**Comment by TrinityCraft** [comment]
nope installed and reinstalled java 8 same thing

**Comment by AndersBillLinden** [comment]
What is the system wide environment variable JAVA_HOME set to?

**Comment by Shane2482** [comment]
Has anybody found a fix for this

**Comment by TrinityCraft** [comment]
Not yet, sorry man. Still looking

**Comment by Shane2482** [comment]
NM I found the prob it is a incompatible graphic drivers prob I just finished rolling back my graphic driver and it works fine now.

**Comment by TrinityCraft** [comment]
Oh ok

**Comment by Shane2482** [comment]
NP glad I could help

**Comment by AndersBillLinden** [comment]
Is this solved?

**Comment by TrinityCraft** [comment]
Not yet

**Comment by sidben** [comment]
I'm having the same problem.

Running the mc-pre4.jar via command line I get this error message:

```
[LWJGL] Initial mode: 1366 x 768 x 32 @60Hz
[LWJGL] Failed to find pixel format with HDC depth 32, falling back to 16

org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at com.mrcrayfish.modelcreator.ModelCreator.<init>(ModelCreator.java:157)
        at com.mrcrayfish.modelcreator.Start.main(Start.java:46)

```

I'm testing this on a notebook with onboard video card, I'll try later on a desktop.

**Comment by rilian4** [comment]
I am having the same problem. NVIDIA GTX 970. Version 378.49. Exact same symptons. My java command line is identical to sidben's except the resolution is 1920x1080.

**Comment by sidben** [comment]
That's strange, that bug happens on my notebook, but on my desktop I have a GTX 550 Ti also running Windows 10 and works like a charm.

From the time I searched it, that error message is related to outdated video drivers. I think your card should work.

**Comment by rilian4** [comment]
You'd think my card would work but it doesn't. I could use ideas... My drivers seem up to date and minecraft, which is also Java based, runs fine.
