### ISSUE TITLE
Black Screen On OS X El Captian

### ISSUE THREAD

**Issue by epiccoder2** [MrCrayfish/ModelCreator#157]
I don't know what is going on. I tried reinstalling it, and nothing.
![screen shot 2019-01-27 at 5 28 14 pm](https://user-images.githubusercontent.com/43425381/51809955-a0663f80-2259-11e9-83ed-09a3c0d17e4d.png)

**Comment by rickirunge** [comment]
Same for me, ind Mojave. Running java 8 (1.8.0_192)

**Comment by strifel** [comment]
Same for me Java 8 Update 201
MacOS 10.14.3

**Comment by hanleybrand** [comment]
Same for me - here's a stack trace

```
$ java -jar mc-0.6.0.jar  --started-by-exe
[LWJGL] Initial mode: 2560 x 1440 x 32 @60Hz
[LWJGL] MemoryUtil Accessor: AccessorUnsafe
Could not locate symbol glClientAttribDefaultEXT
Could not locate symbol glPushClientAttribDefaultEXT
Could not locate symbol glMatrixLoadfEXT
Could not locate symbol glMatrixLoaddEXT
Could not locate symbol glMatrixMultfEXT
Could not locate symbol glMatrixMultdEXT
Could not locate symbol glMatrixLoadIdentityEXT
Could not locate symbol glMatrixRotatefEXT
Could not locate symbol glMatrixRotatedEXT
Could not locate symbol glMatrixScalefEXT
Could not locate symbol glMatrixScaledEXT
Could not locate symbol glMatrixTranslatefEXT
Could not locate symbol glMatrixTranslatedEXT
Could not locate symbol glMatrixOrthoEXT
Could not locate symbol glMatrixFrustumEXT
Could not locate symbol glMatrixPushEXT
Could not locate symbol glMatrixPopEXT
Could not locate symbol glTextureParameteriEXT
Could not locate symbol glTextureParameterivEXT
Could not locate symbol glTextureParameterfEXT
Could not locate symbol glTextureParameterfvEXT
Could not locate symbol glTextureImage1DEXT
Could not locate symbol glTextureImage2DEXT
Could not locate symbol glTextureSubImage1DEXT
Could not locate symbol glTextureSubImage2DEXT
Could not locate symbol glCopyTextureImage1DEXT
Could not locate symbol glCopyTextureImage2DEXT
Could not locate symbol glCopyTextureSubImage1DEXT
Could not locate symbol glCopyTextureSubImage2DEXT
Could not locate symbol glGetTextureImageEXT
Could not locate symbol glGetTextureParameterfvEXT
Could not locate symbol glGetTextureParameterivEXT
Could not locate symbol glGetTextureLevelParameterfvEXT
Could not locate symbol glGetTextureLevelParameterivEXT
Could not locate symbol glTextureImage3DEXT
Could not locate symbol glTextureSubImage3DEXT
Could not locate symbol glCopyTextureSubImage3DEXT
Could not locate symbol glBindMultiTextureEXT
Could not locate symbol glMultiTexCoordPointerEXT
Could not locate symbol glMultiTexEnvfEXT
Could not locate symbol glMultiTexEnvfvEXT
Could not locate symbol glMultiTexEnviEXT
Could not locate symbol glMultiTexEnvivEXT
Could not locate symbol glMultiTexGendEXT
Could not locate symbol glMultiTexGendvEXT
Could not locate symbol glMultiTexGenfEXT
Could not locate symbol glMultiTexGenfvEXT
Could not locate symbol glMultiTexGeniEXT
Could not locate symbol glMultiTexGenivEXT
Could not locate symbol glGetMultiTexEnvfvEXT
Could not locate symbol glGetMultiTexEnvivEXT
Could not locate symbol glGetMultiTexGendvEXT
Could not locate symbol glGetMultiTexGenfvEXT
Could not locate symbol glGetMultiTexGenivEXT
Could not locate symbol glMultiTexParameteriEXT
Could not locate symbol glMultiTexParameterivEXT
Could not locate symbol glMultiTexParameterfEXT
Could not locate symbol glMultiTexParameterfvEXT
Could not locate symbol glMultiTexImage1DEXT
Could not locate symbol glMultiTexImage2DEXT
Could not locate symbol glMultiTexSubImage1DEXT
Could not locate symbol glMultiTexSubImage2DEXT
Could not locate symbol glCopyMultiTexImage1DEXT
Could not locate symbol glCopyMultiTexImage2DEXT
Could not locate symbol glCopyMultiTexSubImage1DEXT
Could not locate symbol glCopyMultiTexSubImage2DEXT
Could not locate symbol glGetMultiTexImageEXT
Could not locate symbol glGetMultiTexParameterfvEXT
Could not locate symbol glGetMultiTexParameterivEXT
Could not locate symbol glGetMultiTexLevelParameterfvEXT
Could not locate symbol glGetMultiTexLevelParameterivEXT
Could not locate symbol glMultiTexImage3DEXT
Could not locate symbol glMultiTexSubImage3DEXT
Could not locate symbol glCopyMultiTexSubImage3DEXT
Could not locate symbol glEnableClientStateIndexedEXT
Could not locate symbol glDisableClientStateIndexedEXT
Could not locate symbol glGetFloatIndexedvEXT
Could not locate symbol glGetDoubleIndexedvEXT
Could not locate symbol glGetPointerIndexedvEXT
Could not locate symbol glNamedProgramStringEXT
Could not locate symbol glNamedProgramLocalParameter4dEXT
Could not locate symbol glNamedProgramLocalParameter4dvEXT
Could not locate symbol glNamedProgramLocalParameter4fEXT
Could not locate symbol glNamedProgramLocalParameter4fvEXT
Could not locate symbol glGetNamedProgramLocalParameterdvEXT
Could not locate symbol glGetNamedProgramLocalParameterfvEXT
Could not locate symbol glGetNamedProgramivEXT
Could not locate symbol glGetNamedProgramStringEXT
Could not locate symbol glCompressedTextureImage3DEXT
Could not locate symbol glCompressedTextureImage2DEXT
Could not locate symbol glCompressedTextureImage1DEXT
Could not locate symbol glCompressedTextureSubImage3DEXT
Could not locate symbol glCompressedTextureSubImage2DEXT
Could not locate symbol glCompressedTextureSubImage1DEXT
Could not locate symbol glGetCompressedTextureImageEXT
Could not locate symbol glCompressedMultiTexImage3DEXT
Could not locate symbol glCompressedMultiTexImage2DEXT
Could not locate symbol glCompressedMultiTexImage1DEXT
Could not locate symbol glCompressedMultiTexSubImage3DEXT
Could not locate symbol glCompressedMultiTexSubImage2DEXT
Could not locate symbol glCompressedMultiTexSubImage1DEXT
Could not locate symbol glGetCompressedMultiTexImageEXT
Could not locate symbol glMatrixLoadTransposefEXT
Could not locate symbol glMatrixLoadTransposedEXT
Could not locate symbol glMatrixMultTransposefEXT
Could not locate symbol glMatrixMultTransposedEXT
Could not locate symbol glNamedBufferDataEXT
Could not locate symbol glNamedBufferSubDataEXT
Could not locate symbol glMapNamedBufferEXT
Could not locate symbol glUnmapNamedBufferEXT
Could not locate symbol glGetNamedBufferParameterivEXT
Could not locate symbol glGetNamedBufferPointervEXT
Could not locate symbol glGetNamedBufferSubDataEXT
Could not locate symbol glProgramUniform1fEXT
Could not locate symbol glProgramUniform2fEXT
Could not locate symbol glProgramUniform3fEXT
Could not locate symbol glProgramUniform4fEXT
Could not locate symbol glProgramUniform1iEXT
Could not locate symbol glProgramUniform2iEXT
Could not locate symbol glProgramUniform3iEXT
Could not locate symbol glProgramUniform4iEXT
Could not locate symbol glProgramUniform1fvEXT
Could not locate symbol glProgramUniform2fvEXT
Could not locate symbol glProgramUniform3fvEXT
Could not locate symbol glProgramUniform4fvEXT
Could not locate symbol glProgramUniform1ivEXT
Could not locate symbol glProgramUniform2ivEXT
Could not locate symbol glProgramUniform3ivEXT
Could not locate symbol glProgramUniform4ivEXT
Could not locate symbol glProgramUniformMatrix2fvEXT
Could not locate symbol glProgramUniformMatrix3fvEXT
Could not locate symbol glProgramUniformMatrix4fvEXT
Could not locate symbol glProgramUniformMatrix2x3fvEXT
Could not locate symbol glProgramUniformMatrix3x2fvEXT
Could not locate symbol glProgramUniformMatrix2x4fvEXT
Could not locate symbol glProgramUniformMatrix4x2fvEXT
Could not locate symbol glProgramUniformMatrix3x4fvEXT
Could not locate symbol glProgramUniformMatrix4x3fvEXT
Could not locate symbol glTextureParameterIivEXT
Could not locate symbol glTextureParameterIuivEXT
Could not locate symbol glGetTextureParameterIivEXT
Could not locate symbol glGetTextureParameterIuivEXT
Could not locate symbol glMultiTexParameterIivEXT
Could not locate symbol glMultiTexParameterIuivEXT
Could not locate symbol glGetMultiTexParameterIivEXT
Could not locate symbol glGetMultiTexParameterIuivEXT
Could not locate symbol glProgramUniform1uiEXT
Could not locate symbol glProgramUniform2uiEXT
Could not locate symbol glProgramUniform3uiEXT
Could not locate symbol glProgramUniform4uiEXT
Could not locate symbol glProgramUniform1uivEXT
Could not locate symbol glProgramUniform2uivEXT
Could not locate symbol glProgramUniform3uivEXT
Could not locate symbol glProgramUniform4uivEXT
Could not locate symbol glNamedProgramLocalParameters4fvEXT
Could not locate symbol glNamedRenderbufferStorageEXT
Could not locate symbol glGetNamedRenderbufferParameterivEXT
Could not locate symbol glNamedRenderbufferStorageMultisampleEXT
Could not locate symbol glCheckNamedFramebufferStatusEXT
Could not locate symbol glNamedFramebufferTexture1DEXT
Could not locate symbol glNamedFramebufferTexture2DEXT
Could not locate symbol glNamedFramebufferTexture3DEXT
Could not locate symbol glNamedFramebufferRenderbufferEXT
Could not locate symbol glGetNamedFramebufferAttachmentParameterivEXT
Could not locate symbol glGenerateTextureMipmapEXT
Could not locate symbol glGenerateMultiTexMipmapEXT
Could not locate symbol glFramebufferDrawBufferEXT
Could not locate symbol glFramebufferDrawBuffersEXT
Could not locate symbol glFramebufferReadBufferEXT
Could not locate symbol glGetFramebufferParameterivEXT
Could not locate symbol glNamedFramebufferTextureEXT
Could not locate symbol glNamedFramebufferTextureLayerEXT
Could not locate symbol glNamedFramebufferTextureFaceEXT
[LWJGL] GL_EXT_direct_state_access was reported as available but an entry point is missing
Could not locate symbol glPrimitiveRestartNV
Could not locate symbol glPrimitiveRestartIndexNV
[LWJGL] GL_NV_primitive_restart was reported as available but an entry point is missing
Could not locate symbol glClientAttribDefaultEXT
Could not locate symbol glPushClientAttribDefaultEXT
Could not locate symbol glMatrixLoadfEXT
Could not locate symbol glMatrixLoaddEXT
Could not locate symbol glMatrixMultfEXT
Could not locate symbol glMatrixMultdEXT
Could not locate symbol glMatrixLoadIdentityEXT
Could not locate symbol glMatrixRotatefEXT
Could not locate symbol glMatrixRotatedEXT
Could not locate symbol glMatrixScalefEXT
Could not locate symbol glMatrixScaledEXT
Could not locate symbol glMatrixTranslatefEXT
Could not locate symbol glMatrixTranslatedEXT
Could not locate symbol glMatrixOrthoEXT
Could not locate symbol glMatrixFrustumEXT
Could not locate symbol glMatrixPushEXT
Could not locate symbol glMatrixPopEXT
Could not locate symbol glTextureParameteriEXT
Could not locate symbol glTextureParameterivEXT
Could not locate symbol glTextureParameterfEXT
Could not locate symbol glTextureParameterfvEXT
Could not locate symbol glTextureImage1DEXT
Could not locate symbol glTextureImage2DEXT
Could not locate symbol glTextureSubImage1DEXT
Could not locate symbol glTextureSubImage2DEXT
Could not locate symbol glCopyTextureImage1DEXT
Could not locate symbol glCopyTextureImage2DEXT
Could not locate symbol glCopyTextureSubImage1DEXT
Could not locate symbol glCopyTextureSubImage2DEXT
Could not locate symbol glGetTextureImageEXT
Could not locate symbol glGetTextureParameterfvEXT
Could not locate symbol glGetTextureParameterivEXT
Could not locate symbol glGetTextureLevelParameterfvEXT
Could not locate symbol glGetTextureLevelParameterivEXT
Could not locate symbol glTextureImage3DEXT
Could not locate symbol glTextureSubImage3DEXT
Could not locate symbol glCopyTextureSubImage3DEXT
Could not locate symbol glBindMultiTextureEXT
Could not locate symbol glMultiTexCoordPointerEXT
Could not locate symbol glMultiTexEnvfEXT
Could not locate symbol glMultiTexEnvfvEXT
Could not locate symbol glMultiTexEnviEXT
Could not locate symbol glMultiTexEnvivEXT
Could not locate symbol glMultiTexGendEXT
Could not locate symbol glMultiTexGendvEXT
Could not locate symbol glMultiTexGenfEXT
Could not locate symbol glMultiTexGenfvEXT
Could not locate symbol glMultiTexGeniEXT
Could not locate symbol glMultiTexGenivEXT
Could not locate symbol glGetMultiTexEnvfvEXT
Could not locate symbol glGetMultiTexEnvivEXT
Could not locate symbol glGetMultiTexGendvEXT
Could not locate symbol glGetMultiTexGenfvEXT
Could not locate symbol glGetMultiTexGenivEXT
Could not locate symbol glMultiTexParameteriEXT
Could not locate symbol glMultiTexParameterivEXT
Could not locate symbol glMultiTexParameterfEXT
Could not locate symbol glMultiTexParameterfvEXT
Could not locate symbol glMultiTexImage1DEXT
Could not locate symbol glMultiTexImage2DEXT
Could not locate symbol glMultiTexSubImage1DEXT
Could not locate symbol glMultiTexSubImage2DEXT
Could not locate symbol glCopyMultiTexImage1DEXT
Could not locate symbol glCopyMultiTexImage2DEXT
Could not locate symbol glCopyMultiTexSubImage1DEXT
Could not locate symbol glCopyMultiTexSubImage2DEXT
Could not locate symbol glGetMultiTexImageEXT
Could not locate symbol glGetMultiTexParameterfvEXT
Could not locate symbol glGetMultiTexParameterivEXT
Could not locate symbol glGetMultiTexLevelParameterfvEXT
Could not locate symbol glGetMultiTexLevelParameterivEXT
Could not locate symbol glMultiTexImage3DEXT
Could not locate symbol glMultiTexSubImage3DEXT
Could not locate symbol glCopyMultiTexSubImage3DEXT
Could not locate symbol glEnableClientStateIndexedEXT
Could not locate symbol glDisableClientStateIndexedEXT
Could not locate symbol glGetFloatIndexedvEXT
Could not locate symbol glGetDoubleIndexedvEXT
Could not locate symbol glGetPointerIndexedvEXT
Could not locate symbol glNamedProgramStringEXT
Could not locate symbol glNamedProgramLocalParameter4dEXT
Could not locate symbol glNamedProgramLocalParameter4dvEXT
Could not locate symbol glNamedProgramLocalParameter4fEXT
Could not locate symbol glNamedProgramLocalParameter4fvEXT
Could not locate symbol glGetNamedProgramLocalParameterdvEXT
Could not locate symbol glGetNamedProgramLocalParameterfvEXT
Could not locate symbol glGetNamedProgramivEXT
Could not locate symbol glGetNamedProgramStringEXT
Could not locate symbol glCompressedTextureImage3DEXT
Could not locate symbol glCompressedTextureImage2DEXT
Could not locate symbol glCompressedTextureImage1DEXT
Could not locate symbol glCompressedTextureSubImage3DEXT
Could not locate symbol glCompressedTextureSubImage2DEXT
Could not locate symbol glCompressedTextureSubImage1DEXT
Could not locate symbol glGetCompressedTextureImageEXT
Could not locate symbol glCompressedMultiTexImage3DEXT
Could not locate symbol glCompressedMultiTexImage2DEXT
Could not locate symbol glCompressedMultiTexImage1DEXT
Could not locate symbol glCompressedMultiTexSubImage3DEXT
Could not locate symbol glCompressedMultiTexSubImage2DEXT
Could not locate symbol glCompressedMultiTexSubImage1DEXT
Could not locate symbol glGetCompressedMultiTexImageEXT
Could not locate symbol glMatrixLoadTransposefEXT
Could not locate symbol glMatrixLoadTransposedEXT
Could not locate symbol glMatrixMultTransposefEXT
Could not locate symbol glMatrixMultTransposedEXT
Could not locate symbol glNamedBufferDataEXT
Could not locate symbol glNamedBufferSubDataEXT
Could not locate symbol glMapNamedBufferEXT
Could not locate symbol glUnmapNamedBufferEXT
Could not locate symbol glGetNamedBufferParameterivEXT
Could not locate symbol glGetNamedBufferPointervEXT
Could not locate symbol glGetNamedBufferSubDataEXT
Could not locate symbol glProgramUniform1fEXT
Could not locate symbol glProgramUniform2fEXT
Could not locate symbol glProgramUniform3fEXT
Could not locate symbol glProgramUniform4fEXT
Could not locate symbol glProgramUniform1iEXT
Could not locate symbol glProgramUniform2iEXT
Could not locate symbol glProgramUniform3iEXT
Could not locate symbol glProgramUniform4iEXT
Could not locate symbol glProgramUniform1fvEXT
Could not locate symbol glProgramUniform2fvEXT
Could not locate symbol glProgramUniform3fvEXT
Could not locate symbol glProgramUniform4fvEXT
Could not locate symbol glProgramUniform1ivEXT
Could not locate symbol glProgramUniform2ivEXT
Could not locate symbol glProgramUniform3ivEXT
Could not locate symbol glProgramUniform4ivEXT
Could not locate symbol glProgramUniformMatrix2fvEXT
Could not locate symbol glProgramUniformMatrix3fvEXT
Could not locate symbol glProgramUniformMatrix4fvEXT
Could not locate symbol glProgramUniformMatrix2x3fvEXT
Could not locate symbol glProgramUniformMatrix3x2fvEXT
Could not locate symbol glProgramUniformMatrix2x4fvEXT
Could not locate symbol glProgramUniformMatrix4x2fvEXT
Could not locate symbol glProgramUniformMatrix3x4fvEXT
Could not locate symbol glProgramUniformMatrix4x3fvEXT
Could not locate symbol glTextureParameterIivEXT
Could not locate symbol glTextureParameterIuivEXT
Could not locate symbol glGetTextureParameterIivEXT
Could not locate symbol glGetTextureParameterIuivEXT
Could not locate symbol glMultiTexParameterIivEXT
Could not locate symbol glMultiTexParameterIuivEXT
Could not locate symbol glGetMultiTexParameterIivEXT
Could not locate symbol glGetMultiTexParameterIuivEXT
Could not locate symbol glProgramUniform1uiEXT
Could not locate symbol glProgramUniform2uiEXT
Could not locate symbol glProgramUniform3uiEXT
Could not locate symbol glProgramUniform4uiEXT
Could not locate symbol glProgramUniform1uivEXT
Could not locate symbol glProgramUniform2uivEXT
Could not locate symbol glProgramUniform3uivEXT
Could not locate symbol glProgramUniform4uivEXT
Could not locate symbol glNamedProgramLocalParameters4fvEXT
Could not locate symbol glNamedRenderbufferStorageEXT
Could not locate symbol glGetNamedRenderbufferParameterivEXT
Could not locate symbol glNamedRenderbufferStorageMultisampleEXT
Could not locate symbol glCheckNamedFramebufferStatusEXT
Could not locate symbol glNamedFramebufferTexture1DEXT
Could not locate symbol glNamedFramebufferTexture2DEXT
Could not locate symbol glNamedFramebufferTexture3DEXT
Could not locate symbol glNamedFramebufferRenderbufferEXT
Could not locate symbol glGetNamedFramebufferAttachmentParameterivEXT
Could not locate symbol glGenerateTextureMipmapEXT
Could not locate symbol glGenerateMultiTexMipmapEXT
Could not locate symbol glFramebufferDrawBufferEXT
Could not locate symbol glFramebufferDrawBuffersEXT
Could not locate symbol glFramebufferReadBufferEXT
Could not locate symbol glGetFramebufferParameterivEXT
Could not locate symbol glNamedFramebufferTextureEXT
Could not locate symbol glNamedFramebufferTextureLayerEXT
Could not locate symbol glNamedFramebufferTextureFaceEXT
[LWJGL] GL_EXT_direct_state_access was reported as available but an entry point is missing
Could not locate symbol glPrimitiveRestartNV
Could not locate symbol glPrimitiveRestartIndexNV
[LWJGL] GL_NV_primitive_restart was reported as available but an entry point is missing
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mrcrayfish.modelcreator.component.TextureManager.addImage(TextureManager.java:287)
	at com.mrcrayfish.modelcreator.Importer.loadTexture(Importer.java:173)
	at com.mrcrayfish.modelcreator.Importer.loadTextures(Importer.java:152)
	at com.mrcrayfish.modelcreator.Importer.readComponents(Importer.java:102)
	at com.mrcrayfish.modelcreator.Importer.importFromJSON(Importer.java:52)
	at com.mrcrayfish.modelcreator.ProjectManager.loadProject(ProjectManager.java:40)
	at com.mrcrayfish.modelcreator.util.Util.loadModelFromJar(Util.java:138)
	at com.mrcrayfish.modelcreator.component.Menu.lambda$initActions$26(Menu.java:380)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hanleybrand** [comment]
This is not the first time this has come u, I guess - https://github.com/MrCrayfish/ModelCreator/issues/116

**Comment by OneSharpAce** [comment]
I would like to add that I was able to capture a screenshot within the app, after adding one cube. The resulting png displays everything correctly except with an overall dark appearance. I'm still looking into it more.

**Comment by mloparco** [comment]
I'm getting the same issue on Mac High Sierra, tried both 0.6 and 0.7. Any insights anyone?

**Comment by MrCrayfish** [comment]
This is unfortunately something hard for me to debug as I don't have a Mac. Did previous versions work or was it only the latest updates?

**Comment by OneSharpAce** [comment]
pre4 worked and at least in my setup continues to work.

**Comment by OneSharpAce** [comment]
Ok, after more research I believe this issues is caused by the bug listed at the two links below. I release this bug relates to windows however some users with windows have reported the same issue. I figure they must somehow be related.

https://bugs.openjdk.java.net/browse/JDK-8195129
https://bugs.openjdk.java.net/browse/JDK-8017274

I have also noticed that LWJGL team has implemented a workaround for the bug in their codebase (if this is indeed the cause) and have an updated SharedLibraryLoader.java file (although it is for LWJGL3) that you could perhaps reference. It is listed below.

https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/SharedLibraryLoader.java

Hopefully this helps to guide you to a solution, I'm trying myself but I am new to java development, and still pretty bad at making heads or tails of others code.

Edited for clarity.

**Comment by Beatzoid** [comment]
> 

> Ok, after more research I believe this issues is caused by the bug listed at the two links below. I release this bug relates to windows however some users with windows have reported the same issue. I figure they must somehow be related.
> 
> https://bugs.openjdk.java.net/browse/JDK-8195129
> https://bugs.openjdk.java.net/browse/JDK-8017274
> 
> I have also noticed that LWJGL team has implemented a workaround (if this is indeed the cause) and have an updated SharedLibraryLoader.java file (although it is for LWJGL3). It is listed below.
> 
> https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/SharedLibraryLoader.java
> 
> Hopefully this helps to guide you to a solution, I'm trying myself but I am new to java development, and still pretty bad at making heads or tails of others code.

Just wondering, where do I place the SharedLibraryLoader file?

**Comment by OneSharpAce** [comment]
> > Ok, after more research I believe this issues is caused by the bug listed at the two links below. I release this bug relates to windows however some users with windows have reported the same issue. I figure they must somehow be related.
> > https://bugs.openjdk.java.net/browse/JDK-8195129
> > https://bugs.openjdk.java.net/browse/JDK-8017274
> > I have also noticed that LWJGL team has implemented a workaround (if this is indeed the cause) and have an updated SharedLibraryLoader.java file (although it is for LWJGL3). It is listed below.
> > https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/SharedLibraryLoader.java
> > Hopefully this helps to guide you to a solution, I'm trying myself but I am new to java development, and still pretty bad at making heads or tails of others code.
> 
> Just wondering, where do I place the SharedLibraryLoader file?

Sorry for the confusion. Their file will not fix the problem, it is just their approach for their own code that is based off a similar codebase. I only included the links so that hopefully MrCrayfish or another, could reference their solution to remedy the issue we are having.

**Comment by OneSharpAce** [comment]
Ok I have made some progress. It now will show the display, however it is still "dark theme" if you will. To get this far I had to also pass in "withAuxBuffers" attribute when the PixelFormat is passed. However I still don't fully know what I am doing so it created more errors. Here is a link to the current state while on macOS.

https://imgur.com/a/3reBtGz

I fear though that it will take a lot of work for compatibility because in testing of the current version, importing and exporting throws errors on macOS.

**Comment by ryancave282** [comment]
This is what happened to me, once I open the application the working area is black and the menus just sit with options that don't work and the app won't even close.

**Comment by ryancave282** [comment]
BTW That was on a **_Windows 10 upgraded Windows 7 Home Premium 64-bit PC_**.

**Comment by ryancave282** [comment]
**https://user-images.githubusercontent.com/51128072/58507648-d9ef7e80-8157-11e9-8636-95587aea9c83.png**!! That image is GREAT news. Now I just have to figure stuff out.

**Comment by OneSharpAce** [comment]
I have managed to debug that part of the issue is that passing zero sized buffer can can cause bugs that are highly system and configuration dependent.

**Comment by ryancave282** [comment]
How did you fix the problem??????

**Comment by Entity303GamingYT** [comment]
@OneSharpAce answer

**Comment by Entity303GamingYT** [comment]
???????????

**Comment by OneSharpAce** [comment]
I'll be home in a minute. I push an experimental release on my branch for you to download and see if it works for you.

**Comment by ryancave282** [comment]
Thank you and don't forget i'm using Windows 10

**Comment by OneSharpAce** [comment]
@Entity303GamingYT It is ready, you can find it in the release section of my fork. I can't promise it will fix it but if you could let me know what it does for you I would appreciate it. Please report what it does in my bug section please as to not flood MrCrayfish.

**Comment by Beatzoid** [comment]
Ok. Will try when I have time. Thank you so much everyone for helping.

**Comment by ryancave282** [comment]
@OneSharpAce  Where's that? Can you send me a link?

**Comment by OneSharpAce** [comment]
> @OneSharpAce Where's that? Can you send me a link?

https://github.com/OneSharpAce/ModelCreator/releases/download/Test/ModelCreator-0.7.0-TEST.jar

**Comment by ryancave282** [comment]
Thank you @OneSharpAce

**Comment by ryancave282** [comment]
@OneSharpAce I just installed it and it didn't fix the bug/problem

**Comment by OneSharpAce** [comment]
@Entity303GamingYT Did it not change anything at all?

**Comment by ryancave282** [comment]
No, nothing.

**Comment by ryancave282** [comment]
The only way to close the app is to restart my PC.

**Comment by Entity303GamingYT** [comment]
HELLO!!!!!!!!!!!!!!!

**Comment by Entity303GamingYT** [comment]
......

**Comment by Entity303GamingYT** [comment]
**@OneSharpAce!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

**Comment by Entity303GamingYT** [comment]
???????????????????????????????????????????????????????????????????????????

**Comment by OneSharpAce** [comment]
@Entity303GamingYT It sounds like you have an issue with your java installation or something with your operating system as a whole. I realize that you're frustrated that the program doesn't work for you. However please realize that I work on things in my spare time, this is also not my original code, so it takes time to understand things, I'm also not nearly as well versed in java as mrcrayfish so there are things in his code that I completely don't understand. Continually spamming messages of question marks, does not encourage anyone to want to help you further.

**Comment by ryancave282** [comment]
What ?s

**Comment by Edudmai** [comment]
Only pre 4 works for me. All of the rest have the black screen problem.

**Comment by kitaboon** [comment]
hello, 
same here for mac high sierra

EDIT : it's working with pre 4 version (thank you Edudmai)

**Comment by UliTroyo** [comment]
Hi! It looks like this issue is still open. I'm having the same problem on macOS Catalina 10.15.3. Would I maybe be able to help you debug something on Mac, Cray? I don't know where to look. Also, thanks OneSharpAce for trying to sort the problem. And thanks for everything, Cray!

**Comment by Caspar215** [comment]
Same here, I haven't tried all the versions, however, mine doesn't even work on Pre4 (No offense Cray)

**Comment by Caspar215** [comment]
Just tried 0.5 and 0.6, none work, if anyone has a fix, pls share.
(No Imgur link cause on Imgur it looks like it works, but it doesn't work IRL)
P.S. I use MacOS 1.15

**Comment by electroknight** [comment]
i have been having that problem as well very thing works exept you can't see it
