### ISSUE TITLE
Maybe my error

### ISSUE THREAD

**Issue by DenOwq** [MrCrayfish/ModelCreator#52]
If i run ModelCreator with console it's say:
```Java
org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at com.mrcrayfish.modelcreator.ModelCreator.<init>(ModelCreator.java:157)
        at com.mrcrayfish.modelcreator.Start.main(Start.java:46)
```
I normaly can run Minecraft.

**Comment by mateuszdrwal** [comment]
Strange, minecraft gave me that error once before. Try updating your java and graphics drivers

**Comment by DenOwq** [comment]
i do it, no work

**Comment by spaceemotion** [comment]
What is your graphics card? My guess is that its an integrated Intel card, but I might be wrong.

**Comment by mateuszdrwal** [comment]
I got 2, one integrated intel and one amd radeon. That error i talked about was when my drivers for the amd wernt working and my computer was using the intel. I dont think the program works with those cards. Anyway, im not an hardware expert at all but the card can probably be the reason why it isnt working for you.

**Comment by spaceemotion** [comment]
That's what I thought. The Intel cards seem to be using software acceleration, while the Pixmap format seems to require proper hardware. As minecraft works with the Intel cards as well, one should be able to fix it for this editor as well.

**Comment by mateuszdrwal** [comment]
i have no idea about what you just said as im not familliar at all with hardware, but this seems like an user problem and not an program bug. maby im wrong, but in that case this issue is closed.

**Comment by spaceemotion** [comment]
@mateuszdrwal This might very well be a bug.
If @DenOwq can run minecraft just fine, and the ModelCreator does not work, there's an issue in this program.

@MrCrayfish The difference between yours and Minecraft lies in ModelCreator:157, in which Minecraft uses a different pixmap format: `Display.create((new PixelFormat()).withDepthBits(24));`
