### ISSUE TITLE
Does not work on Windows 10. 

### ISSUE THREAD

**Issue by PourBrough** [MrCrayfish/ModelCreator#67]
I'm running Java 8 JDK on Windows 10 and the grid or renders does not show up in pre4, pre3, or pre2. Stopped trying after that. I was really hoping to use it because it's the only tool I've found so far specifically designed for Minecraft (16x16 grid). Hoping you update it sometime this Summer. Take care of University first.

http://i.imgur.com/umqfgD8.png

**Comment by ThePuzzlemaker** [comment]
Happened to me, too.

**Comment by MrCrayfish** [comment]
Can you run the program from the command line? It should print out any errors.

**Comment by Tillymaster** [comment]
@MrCrayfish  Same :( .
If I start the programm it looks like this: http://i.imgur.com/xrKKQeP.jpg

I tried it with the command line and got no error: http://i.imgur.com/b9jqqn5.jpg

**Comment by MrCrayfish** [comment]
Use the universal version, and type in "java -jar mc-pre4.jar"

**Comment by Tillymaster** [comment]
Were i should type in "java-jar-mc-pre4.jar"?

**Comment by MrCrayfish** [comment]
Command line

**Comment by Tillymaster** [comment]
it still doesen't work

**Comment by Azoraqua** [comment]
Make sure you type "java -jar mc-pre4.jar", notice the spaces in it.

**Comment by Tillymaster** [comment]
@Azoraqua @MrCrayfish Now I got an Error: http://i.imgur.com/CVpsjeF.jpg

**Comment by Azoraqua** [comment]
@Tillymaster It's commonly caused by outdated graphic drivers or unsupported ones.

Try to update your graphic drivers. 
Alternately you can try to run the command "java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar mc-pre4.jar".
However this command might possibly not work.

Please let me/us know what's the result :)

**Comment by Tillymaster** [comment]
@Azoraqua I upedated the graphic driver. I also tried it with 
"java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar mc-pre4.jar". It still does not work...

**Comment by Azoraqua** [comment]
Strange... Is there any output?

**Comment by Tillymaster** [comment]
No... Nothing

**Comment by Azoraqua** [comment]
Strange... Then I can't help anymore, I am sorry.

**Comment by Tillymaster** [comment]
ok, Thanks anyway

**Comment by ThePuzzlemaker** [comment]
Got an error:

> [LWJGL] Initial mode: 1366 x 768 x 32 @60Hz
[LWJGL] Failed to find pixel format with HDC depth 32, falling back to 16

org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at com.mrcrayfish.modelcreator.ModelCreator.<init>(ModelCreator.java:157)
        at com.mrcrayfish.modelcreator.Start.main(Start.java:46)

**Comment by Tillymaster** [comment]
@ThePuzzlemaker 
I already wrote this error in here...

**Comment by AndersBillLinden** [comment]
Maybe migrating to LWJGL3 is the way out? It would be a major change and the guidelines for doing so can be read on https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.6-LWJGL3-migration.

**Comment by darthvader45** [comment]
Weird, I can't get it to run at all.  The little busy circle appears for a half-second, then nothing at all.  This came from trying to run the .exe file, which Norton 360 thinks is a virus.

**Comment by TommyVic** [comment]
Hi i got a same problem here with window 7 pls help it doen't show up

**Comment by ryancave282** [comment]
It really doesn't work on windows 10. I'm using an **_updated Windows 7 Home Premium 64-bit PC_** and once I open the application the working area is black and the menus just sit with options that don't work and the app won't even close. So Crayfish here's a solution: FIX YOUR BUGGY APPLICATION!!!!!!!
